### ISSUE TITLE
Escript crashes when checking a LiveComponent

### ISSUE THREAD

**Issue by yonkeltron** [Multiverse-io/eextoheex#7]
Hey there!

Thanks for providing such a wonderfully helpful tool! 

## Bug Description

Unfortunately, when trying to run `eextoheex check` on our `templates` directory, the escript produced an error. Below I have provided the error in question, and have edited it for privacy as little as possible.

```
** (FunctionClauseError) no function clause matching in EexToHeex.mung_live_component/1

    The following arguments were given to EexToHeex.mung_live_component/1:

        # 1
        {:live_component, [line: 1], [{:@, [line: 1], [{:socket, [line: 1], nil}]}, {:__aliases__, [line: 2], [:AppWeb, :PageLive, :TypeaheadComponent]}, [id: :typeahead, search_options: {:@, [line: 4], [{:slt_plus_one_options, [line: 4], nil}]}, form: {:f, [line: 5], nil}, form_input_id: :slt_plus_one_id, search_placeholder: "Search"]]}

    (eextoheex 0.1.5) lib/eextoheex.ex:360: EexToHeex.mung_live_component/1
    (eextoheex 0.1.5) lib/eextoheex.ex:346: anonymous fn/2 in EexToHeex.livecomponent_replacements/2
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (eextoheex 0.1.5) lib/eextoheex.ex:46: EexToHeex.eex_to_heex/1
    (eextoheex 0.1.5) lib/eextoheex_cli.ex:88: anonymous fn/3 in EexToHeex.CLI.templates_helper/4
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (eextoheex 0.1.5) lib/eextoheex_cli.ex:85: EexToHeex.CLI.templates_helper/4
```

## Key Info

We ran this on macOS with an escript built from source using Elixir `1.13.4-otp-25`.

Please let me know what additional information I can furnish or if there's any other testing I could do.

Thanks,
+Jonathan

**Comment by addrummond** [comment]
Hey Jonathan, sorry for the late response.

This appears to be an issue with https://github.com/Multiverse-io/eextoheex/pull/4

I didn't write that part of the code, so I'm not immediately sure what the problem is. It would be useful to have a file that triggers the error.
